version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      typescript:
        patterns:
          - 'typescript'
          - '@typescript-eslint/*'
          - 'tsup'
      test:
        patterns:
          - 'vitest'
          - '@vitest/*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
